"""filmlere aciklama eklendi

Revision ID: 303221c98e8f
Revises: 73c21c0d785d
Create Date: 2026-08-19 10:12:36.945277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '303221c98e8f'
down_revision: Union[str, Sequence[str], None] = '73c21c0d785d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filmler', sa.Column('aciklama', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filmler', 'aciklama')
    # ### end Alembic commands ###
