"""kullanicilar tablosu eklendi

Revision ID: e4fbbe27d02b
Revises: 303221c98e8f
Create Date: 2026-08-19 13:32:00.688641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e4fbbe27d02b'
down_revision: Union[str, Sequence[str], None] = '303221c98e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullanici_adi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sifre_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kullanicilar_kullanici_adi'), 'kullanicilar', ['kullanici_adi'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kullanicilar_kullanici_adi'), table_name='kullanicilar')
    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
