name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: test-secret-key-for-github-actions
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      DATABASE_URL: sqlite:///test.db

    steps:
      - name: Download repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked

      - name: Run tests
        run: uv run pytest -v